# Generated by Django 3.1.7 on 2021-04-21 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата старта')),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='Дата окончания')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('TA', 'Text answer'), ('OA', 'One answer'), ('MA', 'Multiple answers')], max_length=2)),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('interrogation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interrogation_app.interrogation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('one_answer', models.CharField(blank=True, choices=[('A', 'OPTION A'), ('B', 'OPTION B'), ('C', 'OPTION C'), ('D', 'OPTION D')], max_length=1, null=True, unique=True)),
                ('multiple_answers', models.CharField(blank=True, choices=[('A', 'OPTION A'), ('B', 'OPTION B'), ('C', 'OPTION C'), ('D', 'OPTION D')], max_length=4, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interrogation_app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
