# Generated by Django 3.0.5 on 2021-04-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interrogation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='one_answer',
            new_name='first_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_a',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_b',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_c',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_d',
            new_name='D',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='multiple_answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='fourth_answer',
            field=models.CharField(blank=True, choices=[('A', 'OPTION A'), ('B', 'OPTION B'), ('C', 'OPTION C'), ('D', 'OPTION D')], max_length=1, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='second_answer',
            field=models.CharField(blank=True, choices=[('A', 'OPTION A'), ('B', 'OPTION B'), ('C', 'OPTION C'), ('D', 'OPTION D')], max_length=1, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='third_answer',
            field=models.CharField(blank=True, choices=[('A', 'OPTION A'), ('B', 'OPTION B'), ('C', 'OPTION C'), ('D', 'OPTION D')], max_length=1, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
